name: icare
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.1.0
  cupertino_icons: ^1.0.2
  get:
  intl_phone_number_input: ^0.7.3+1
  calendar_date_picker2: ^0.5.2
  lottie: ^1.2.1
  font_awesome_flutter: ^10.4.0
  webview_flutter: ^4.2.0
  google_maps_flutter: ^2.2.6
  geolocator: ^9.0.2
  http: ^0.13.6
  google_fonts: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/heart.png"

flutter:
  
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/static/Lora-SemiBold.ttf
        - asset: assets/fonts/static/Lora-BoldItalic.ttf

    - family: Lora
      fonts:
        - asset: assets/fonts/static/Lora-SemiBold.ttf
        - asset: assets/fonts/static/Lora-BoldItalic.ttf
        
  
  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  uses-material-design: true
  
